[profile.default]
solc = "0.8.27"
src = "src"
out = "out"
libs = ["dependencies"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read-write", path = "./script/target/" },
]
remappings = [
    "forge-std/=dependencies/forge-std-1.9.4/src/",
    "foundry-devops/=dependencies/foundry-devops-0.2.2/src/",
    "openzeppelin/=dependencies/@openzeppelin-contracts-5.1.0/",
    "murky/=dependencies/murky-0.1.0/",
]

[dependencies]
forge-std = { version = "1.9.4" }
foundry-devops = { version = "0.2.2" }
"@openzeppelin-contracts" = { version = "5.1.0" }
"murky" = { version = "0.1.0", git = "https://github.com/dmfxyz/murky.git", tag = "v0.1.0" }

[soldeer]
remappings_generate = false
remappings_regenerate = false

[fuzz]
runs = 256

[invariant]
runs = 128
depth = 128
fail_on_revert = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
